/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import ModelGLTF from '@asset/scene.gltf'

export default function Model (props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(ModelGLTF)
  useFrame(({ clock }) => {
    const time = clock.getElapsedTime() * 0.05
    group.current.rotation.set(time, -time, time)
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_Cube004_1.geometry}
          material={materials.Red}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_Cube004_2.geometry}
          material={nodes.Cube001_Cube004_2.material}
        />
      </group>
      <mesh
        receiveShadow
        geometry={nodes.Cube_Cube003.geometry}
        material={materials.LightBrown}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          receiveShadow
          geometry={nodes.Icosphere_1.geometry}
          material={materials.Blue}
        />
        <mesh
          receiveShadow
          geometry={nodes.Icosphere_2.geometry}
          material={materials.Green}
        />
        <mesh
          receiveShadow
          geometry={nodes.Icosphere_3.geometry}
          material={materials.Snow}
        />
        <mesh
          receiveShadow
          geometry={nodes.Icosphere_4.geometry}
          material={materials.Brown}
        />
        <mesh
          receiveShadow
          geometry={nodes.Icosphere_5.geometry}
          material={materials.DarkGreen}
        />
      </group>
      <mesh
        castShadow
        geometry={nodes.Icosphere001_Icosphere002.geometry}
        material={nodes.Icosphere001_Icosphere002.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        geometry={nodes.Icosphere002_Icosphere003.geometry}
        material={nodes.Icosphere002_Icosphere003.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        geometry={nodes.Icosphere003_Icosphere004.geometry}
        material={nodes.Icosphere003_Icosphere004.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        geometry={nodes.Icosphere004_Icosphere005.geometry}
        material={nodes.Icosphere004_Icosphere005.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload(ModelGLTF)
